{
    "name": "Barcode Scanner",
    "version": "18.0.1.0.0",
    "category": "Inventory/Logistics",
    "summary": "Core barcode scanning application for warehouse operations",
    "author": "Binhex, Odoo Community Association (OCA)",
    "website": "https://github.com/RocketCloudSaaS/barcode",
    "maintainers": ["szalatyzuzanna"],
    "license": "LGPL-3",
    "depends": [
        "barcodes",
        "web",
        "stock",
        "stock_move_line_qty_picked",
        "hr",
    ],
    "data": [
        "security/security.xml",
        "views/action.xml",
        "views/stock_picking_views.xml",
        "views/stock_location_views.xml",
        "views/templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "barcode_scanner/static/src/scss/barcode_scanner.scss",
            "barcode_scanner/static/src/xml/barcode_scanner_templates.xml",
            "barcode_scanner/static/src/js/barcode_parser.js",
            "barcode_scanner/static/src/js/barcode.js",
            "barcode_scanner/static/src/js/api.js",
            "barcode_scanner/static/src/js/router.js",
            "barcode_scanner/static/src/js/store.js",
            "barcode_scanner/static/src/js/app.js",
            "barcode_scanner/static/src/js/services/feedback_service.js",
            "barcode_scanner/static/src/js/services/barcode_scanner_state.js",
            "barcode_scanner/static/src/js/services/barcode_scanner_sync.js",
            "barcode_scanner/static/src/js/hooks/use_barcode.js",
            "barcode_scanner/static/src/js/hooks/use_barcode_handler.js",
            "barcode_scanner/static/src/js/hooks/use_inventory.js",
            "barcode_scanner/static/src/js/screens/main_screen.js",
            "barcode_scanner/static/src/js/screens/warehouse_ops.js",
            "barcode_scanner/static/src/js/screens/picking_screen.js",
            "barcode_scanner/static/src/js/screens/picking_list_screen.js",
            "barcode_scanner/static/src/js/screens/employee_selector_screen.js",
            "barcode_scanner/static/src/js/screens/move_wizard_screen.js",
            "barcode_scanner/static/src/js/screens/location_selector_screen.js",
            "barcode_scanner/static/src/js/screens/product_selector_screen.js",
            "barcode_scanner/static/src/js/screens/internal_transfer_screen.js",
            "barcode_scanner/static/src/js/screens/quick_info.js",
            "barcode_scanner/static/src/js/components/picking_move_card.js",
            "barcode_scanner/static/src/js/components/picking_move_list.js",
            "barcode_scanner/static/src/js/components/picking_done_card.js",
            "barcode_scanner/static/src/js/components/picking_done_list.js",
            "barcode_scanner/static/src/js/components/image_viewer.js",
            "barcode_scanner/static/src/js/components/picking_info_tab.js",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
